project_id = "dckxzktipfjdjqjceazd"

[functions.lookup-barcode]
verify_jwt = true

[functions.suggest-oil-alternatives]
verify_jwt = true

[functions.generate-recipe]
verify_jwt = true

[functions.chat]
verify_jwt = true

[functions.certify-restaurant]
verify_jwt = false

[functions.generate-challenge-token]
verify_jwt = true

[functions.validate-challenge-token]
verify_jwt = true
